### ISSUE TITLE
WebSocket Connection Error 401 in MacOS Safari

### ISSUE THREAD

**Issue by MizterB** [hassio-addons/addon-vscode#16]
# Problem/Motivation

The 2.0 version of this add-on does not load in MacOS Mojave Safari

## Expected behavior

VC Code should load and present the full interface

## Actual behavior

A blank screen is presented to the user.  In the browser's developer console the message "WebSocket connection to 'ws://hassio:1337/' failed: Unexpected response code: 401" is repeatedly displayed.

Browsing to the same URL on the same machine using Chrome works fine - there are no WebSocket errors.

## Steps to reproduce

Navigate to `http://hassio:1337` in MacOS Safari, and compare to the same in Chrome on the same machine.  Yes, I have intentionally turned off SSL in this setup - not sure if enabling SSL changes the behavior.

## Proposed changes

I had a similar issue when using an early version of the add-on in the Edge repo.  I believe this was before the NGINX proxy was built in.  I got that version working behind my own proxy by following the instructions here:
https://github.com/codercom/code-server/blob/master/doc/self-hosted/index.md#nginx-reverse-proxy
I believe you need to add `proxy_set_header Accept-Encoding gzip;` per those instructions, which I don't see currently enabled in the latest version of the add-on.

## Screenshots
Safari
<img width="1120" alt="" src="https://user-images.githubusercontent.com/5458030/55327673-97137200-5458-11e9-8511-24d6776bbafa.png">
Chrome
<img width="1284" alt="" src="https://user-images.githubusercontent.com/5458030/55327688-9e3a8000-5458-11e9-9a11-e967d1fd006c.png">

<blockquote><img src="https://avatars2.githubusercontent.com/u/20144034?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/codercom/code-server">codercom/code-server</a></strong></div><div>Run VS Code on a remote server. Contribute to codercom/code-server development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
This has been fixed in add-on release v0.3.0

**Comment by MizterB** [comment]
Unfortunately, I’m still seeing a blank screen and websocket errors after upgrading.

**Comment by frenck** [comment]
That sounds like a different problem. Just checked again:

![image](https://user-images.githubusercontent.com/195327/56152931-561d7080-5fb5-11e9-925e-290ab5a5b862.png)

**Comment by disrupted** [comment]
@MizterB I am having the same issue with blank screen and websocket errors but think it's related to my nginx reverse proxy setup. it works when I browse to the local address.
