### ISSUE TITLE
Out of control CPU while using

### ISSUE THREAD

**Issue by tekHudson** [hassio-addons/addon-vscode#800]
# Problem/Motivation

> I heard the fan on my machine going nuts.

`top` showed 95+% CPU consuption with no process showing any consumption.
<img width="1479" alt="Screen Shot 2024-03-28 at 7 46 36 AM" src="https://github.com/hassio-addons/addon-vscode/assets/6435726/754e8273-8fb3-48c2-baa2-c3eb13ba3932">

The `htop` didn't help much either.
![Screenshot 2024-03-28 at 1 16 14 PM](https://github.com/hassio-addons/addon-vscode/assets/6435726/9830b033-7e4e-4d5a-a774-35a3774c0d6e)

Awhile had passed and the CPU seemed to have started to wind down (i was working so could only deal with this on and off).
I had a break so I went to VScode to check my logs and immediatly heard the Fan go nuts.

I looked at the VScode addon page
![31f973e5c1b8805394d6280f001af462a006f4b4](https://github.com/hassio-addons/addon-vscode/assets/6435726/e6790423-cf94-43d5-8d47-b2361c945552)

## Expected behavior

> Runs smoothly?

## Actual behavior

> see above

## Steps to reproduce

> not sure

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by BradenJ6164** [comment]
I am also having this issue.

**Comment by PiotrMachowski** [comment]
I have also experienced this issue. In my case it seems to be caused by opening `/` directory instead of `/config`.

**Comment by Egglestron** [comment]
Same issue found thanks to the Glances add-on: 10 GB of RAM and 80% CPU usage. Happened while going in and out of Visual Studio Code, maybe a new instance is launched every time.

**Comment by Rindula** [comment]
This issue happens on my side too, by restarting the addon, the issue is solved. Also, Ram Usage seems also to be affected.

As soon as I open the VS Code Tab the usage spikes as seen below and falls down when closing the tab, but still rises without code being opened (nstance running in background)

![image](https://github.com/hassio-addons/addon-vscode/assets/20195655/f653b976-2bd6-4f5c-b376-a015a0692e97)

**Comment by Destroyer061090** [comment]
same problem here... i was thinking problem was relate to HA core but now im sure its VS code. Im running everhing in docker container.

https://github.com/home-assistant/core/issues/119796

**Comment by mhoogenbosch** [comment]
I have issues with CPU too, but a little bit different. When watching the release party I saw a jump page with links to all Addons. I love the approach so I decided to create this too.

I have a entities card with :

```
type: entities
entities:
  - type: weblink
    name: Studio Code Server
    url: /hassio/ingress/a0d7b954_vscode
    icon: mdi:microsoft-visual-studio-code
```

This makes the page just start. But it seems it is not closing it. It just opens more sessions.

Is this the same issue, or the same cause, or should I open a new one?

**Comment by marciogranzotto** [comment]
@frenck can you release a new version of this add-on? Looks like this may be related with a bug on add-ons that use devcontainers. This was fixed back in April: https://github.com/microsoft/vscode-remote-release/issues/9586

**Comment by bkbartk** [comment]
I experience the same issue,
but only if I open the folder `/`
If I open the default folder `/config` memory usage seems to be more stable

**Comment by theyo-tester** [comment]
> I experience the same issue, but only if I open the folder `/` If I open the default folder `/config` memory usage seems to be more stable


Yes I can confirm this too!
I think it has to do with the amount of files vs code (or the Home Assistant Config Helper extension) has to watch for or scan.  So make sure you just use the correct folder in your workspace:  _Three lines => File => Open Folder..._  or just press CTRL + O and make sure you are working in the _"/homeassistant/"_ folder
![image](https://github.com/user-attachments/assets/ddcaf1c7-7376-43a7-bd29-1fa64de433fe)
And  if it is absolutely necessary change it to "/" only temporary, and don't forget to go back to the right folder afterwards :)

I've also noticed that the autocompletion feature served by the Home Assistant Config Helper extension does not work (an issue that multiple persons have complained about), if you are not in the right folder. 

I spent hours banging my head around why the autocompletion did not work and why it used so much CPU 🤦‍♂️

Just my 2 cents :D

BR

**Comment by Rindula** [comment]
@frenck Could this be noted somewhere in the docs as some sort of warning to not use/open the root folder?

**Comment by tjorim** [comment]
> @frenck Could this be noted somewhere in the docs as some sort of warning to not use/open the root folder?

Feel free to open a PR.

**Comment by amagnolo** [comment]
Selecting /homeassistant/ as working folder doesn't solve the issue of high CPU usage in my case. 
Not so long ago this add-on used to work all right with "/" as working folder (that's what I need). CPU usage was nearly 0% when not actively using VScode; right now I have to explicitly stop the add-on when I finish using it, otherwise it melts my rpi4.

**Comment by amagnolo** [comment]
As a workaround, I found the the "file editor" add-on lets you work in "/" files if you disable the default option "Enforce Basepath".
That add-on consumes 0% CPU when unused.

**Comment by banan77** [comment]
Still not solved, the addon is unusable, at least on RPI

**Comment by mhoogenbosch** [comment]
I'm using the 'workaround' too because I haven't seen a new release, or anything related to solving this issue. I'd rather use vscode, but very much not usable. I need to restart the addon every time I've used it.

**Comment by antoweb** [comment]
After last update same problem. My Rasoberry goes 32 load average and rebooted itself

**Comment by eikowagenknecht** [comment]
Same here, on both a Raspi 4 and a Raspi 5 this addon creates a lot of CPU load, even when not actively used.

I have always only used the `/config` folder, so it should not be the `/` problem.

This is a typical load on my Raspi 5 after using it once and then leaving it alone for days.
Using it multiple times makes the problem worse (maybe multiple instances?).

Maybe related (or not), autocomplete and linter sometimes take a few minutes.

![image](https://github.com/user-attachments/assets/b0ecf58c-8039-407d-a430-0e0b308292c5)

My "workaround" is to manually stop the addon after using it and then restart it as needed.

**Comment by metbril** [comment]
Upgrade from 5.7.1 to 5.7.2 made my cpu usage for the add on spike from 2% to 30%. I've downgraded.

**Comment by emufan** [comment]
> I've downgraded.

How did you do it?

**Comment by minmaxat** [comment]
i think the problem still exist - any new ideas
think this problems are the same:
[#884 ](https://github.com/hassio-addons/addon-vscode/issues/884)
[#900  ](https://github.com/hassio-addons/addon-vscode/issues/900)
[#891 ](https://github.com/hassio-addons/addon-vscode/issues/891)
[#565  ](https://github.com/hassio-addons/addon-vscode/issues/565)

**Comment by rhpijnacker** [comment]
Same problem here. Stopped using the addon for now, but I would love this to be fixed.

**Comment by davidrapan** [comment]
> How did you do it?

Your only option is restore from partial backup.

**Comment by metbril** [comment]
Keep open please

**Comment by bkbartk** [comment]
could this one be related?
https://github.com/coder/code-server/issues/5201

**Comment by alexsaas** [comment]
Unfortunately, no one takes care of that. Since September 2024. 😥

**Comment by Coder84619** [comment]
High CPU and RAM usage. Latest 2025.1 and all updates. Happened numerous times the last few weeks.

![Image](https://github.com/user-attachments/assets/72ce3100-4127-4b87-b968-6e8263efb9a5)

**Comment by Janhsen** [comment]
Same here

**Comment by theyo-tester** [comment]
> > I experience the same issue, but only if I open the folder `/` If I open the default folder `/config` memory usage seems to be more stable
> 
> Yes I can confirm this too! I think it has to do with the amount of files vs code (or the Home Assistant Config Helper extension) has to watch for or scan. So make sure you just use the correct folder in your workspace: _Three lines => File => Open Folder..._ or just press CTRL + O and make sure you are working in the _"/homeassistant/"_ folder ![image](https://github.com/user-attachments/assets/ddcaf1c7-7376-43a7-bd29-1fa64de433fe) And if it is absolutely necessary change it to "/" only temporary, and don't forget to go back to the right folder afterwards :)
> 
> I've also noticed that the autocompletion feature served by the Home Assistant Config Helper extension does not work (an issue that multiple persons have complained about), if you are not in the right folder.
> 
> I spent hours banging my head around why the autocompletion did not work and why it used so much CPU 🤦‍♂️
> 
> Just my 2 cents :D
> 
> BR

Tbh, after I corrected this (in short: **change working directory to _"/homeassistant/"_ folder**) the issues with constant high CPU usage are gone. Further, entity and service autocompletion is also working now!

So guys please check this and report if it helped!
Regards!

**Comment by alexsaas** [comment]
Using /config/ as the working dir ✓
Please also check the config_path in the vs code addon configuration. Should be empty ✓

Unfortunately the problem still persists for me. But thank you nonetheless. It was worth a try.
https://github.com/hassio-addons/addon-vscode/issues/891

**Comment by davidrapan** [comment]
> Using /config/ as the working dir ✓
Please also check the config_path in the vs code addon configuration. Should be empty ✓

> Unfortunately the problem still persists for me. But thank you nonetheless. It was worth a try.

Same;

**Comment by theyo-tester** [comment]
Interesting. What hardware are you using? It might be a hardware limitation.

For instance, I don't use an rPi because, in my opinion, it doesn't have enough resources for every possible add-on on HASS. The VS Code add-on, in particular, is resource-intensive.

**Comment by davidrapan** [comment]
HW is irrelevant. It worked before just fine w/ ~v5.16

Anyway, the problem is probably with vscode itself...

**Comment by AJolly** [comment]
Is there any way to downgrade and run the older version?

**Comment by davidrapan** [comment]
Yes, but only using Backup & restore feature of HA.

**Comment by AJolly** [comment]
> Yes, but only using **Backup & restore** feature of HA.

Do you have a backup copy of just the VS code isntance?  

I did sort of work around it by just killing the addon every 30min.
alias: Stop VS Code every 30m
description: ""
triggers:
  - trigger: time_pattern
    minutes: /30
conditions: []
actions:
  - data:
      addon: a0d7b954_vscode
    action: hassio.addon_stop

**Comment by davidrapan** [comment]
The addon still needs a restart after each use to free up resources.

**Comment by LucidityCrash** [comment]
ping 👍

**Comment by OptimusGREEN** [comment]
I wondered why haos was using so much host cpu so installed the glances addon and see it was vscode addon. stopped it and what a difference. Unfortunately ive since had to start putting my central heating back on ;)

**Comment by fernbrun** [comment]
Same here

**Comment by brianGit78** [comment]
Still an issue, just want to prevent the github actions bot from closing this out, it'd be great if this can be fixed.

**Comment by RaveGun** [comment]
What will be a good alternative to vscode for configuration editing?

**Comment by bkbartk** [comment]
> What will be a good alternative to vscode for configuration editing?

File Editor?

**Comment by davidrapan** [comment]
I'm currently just restarting VS Code after each use and it's annoying but it works. :)

**Comment by philcollins012345** [comment]
Idem for me. Did implement an automation to reset SCS 

- id: restart_studio_code_server          when using Studio CS intensively, its CPU consumption increases constantly -> restart
  alias: System - Studio Code Server restart
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id: sensor.studio_code_server_pourcentage_du_processeur
      above: 40
      for: "00:01:00"

  actions:
    - action: notify.persistent_notification
      data:
        message: "Restart SCS ({{now().hour}}:{{now().minute}}:{{now().second}})
        Studio Code Server restarting ; CPU usage is : {{states('sensor.studio_code_server_pourcentage_du_processeur')}}"
    - action: hassio.addon_restart
      data:
        addon: a0d7b954_vscode

**Comment by ZacTyAdams** [comment]
Started having this issue in a Proxmox VM install of the HA and the VSCode add on around 4 weeks ago for some reason. No matter what node in my cluster I put it on it will eventually eat all available CPU and RAM resources. Restarting the Add-On does not resolve the problem either, it immediately fills all available resources as soon as it starts.

<img width="1170" alt="Image" src="https://github.com/user-attachments/assets/011bbb82-94ba-46dd-8f80-9e8b2cb4ea0c" />

![Image](https://github.com/user-attachments/assets/39c85465-c205-4258-a177-e2e0a3248d85)

![Image](https://github.com/user-attachments/assets/6a63e401-e5df-4496-bf06-761dbb427d3a)

[a0d7b954_vscode_2025-06-05T16-32-33.876Z.log](https://github.com/user-attachments/files/20614724/a0d7b954_vscode_2025-06-05T16-32-33.876Z.log)

**Comment by dm82m** [comment]
Still a problem

**Comment by philcollins012345** [comment]
Same for me

**Comment by Mackamuir** [comment]
The problem is with the extension https://github.com/keesschollaart81/vscode-home-assistant, not this repo

**Comment by metbril** [comment]
Related to https://github.com/keesschollaart81/vscode-home-assistant/issues/2656 ?

**Comment by LucidityCrash** [comment]
@rsperry79 proved it was an issue with how this adding installs the extensions and fixed it but the PR was rejected as being too complex as it also fixed some other things but no one has taken it further

**Comment by slogen** [comment]
I am hit too for a long time -- using ~150% CPU on a 2-cpu proxmox installation.  the /config workaround mentioned earlier by @PiotrMachowski improves things back to being usable and having load <5%.

- Studio Code Server 5.19.3
- Homeassistant OS 16.2
- Supervisor 2025.09.0
- Core 2025.9.3
- Frontend 20250903.5

**Comment by philcollins012345** [comment]
Still a problem for me too

**Comment by oekiwoeki** [comment]
I also have the same problem.

**Comment by DerekSeaman** [comment]
Thank you! Had major CPU problems this week! Have to resort to stopping the add-on when I'm not using.

**Comment by frenck** [comment]
Please try the latest release: https://github.com/hassio-addons/addon-vscode/releases/tag/v6.0.0

I'm curious to learn if things improved.

../Frenck  

<p>
  <a href="https://www.linkedin.com/in/frenck/"><img src="https://github.com/frenck/frenck/raw/main/images/linkedin.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://youtube.com/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/youtube.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://bsky.app/profile/frenck.social"><img src="https://github.com/frenck/frenck/raw/main/images/bluesky.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://fosstodon.org/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/mastodon.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.instagram.com/frenck/"><img src="https://github.com/frenck/frenck/raw/main/images/instagram.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.threads.net/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/threads.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.facebook.com/frenck.dev/"><img src="https://github.com/frenck/frenck/raw/main/images/facebook.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://x.com/frenck"><img src="https://github.com/frenck/frenck/raw/main/images/x.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.tiktok.com/@frenck.nl"><img src="https://github.com/frenck/frenck/raw/main/images/tiktok.svg" width="18" height="18"></a>
</p>

Blogging my personal ramblings at <a href="https://frenck.dev">frenck.dev</a>

**Comment by fernbrun** [comment]
How do you create sensor 

> lias: "System: Restart VS code addon"
> description: ""
> triggers:
>   - trigger: numeric_state
>     entity_id:
>       - sensor.studio_code_server_cpu_percent
>     above: 40
>     for:
>       hours: 0
>       minutes: 5
>       seconds: 0
> conditions: []
> actions:
>   - action: hassio.addon_restart
>     data:
>       addon: a0d7b954_vscode
>   - action: notify.persistent_notification
>     metadata: {}
>     data:
>       message: "Restarted VS Code addon due to excessive CPU usage."
> mode: single

How do you create sensor ? studio_code_server_cpu_percent

**Comment by 1iverea9er** [comment]
In my case, the good news is that resources are not consumed when the VSCode window is inactive (without stopping the add-on). However, when it is active, it still consumes a lot of resources. Apparently, this is already similar to normal behavior.

<img width="825" height="435" alt="Image" src="https://github.com/user-attachments/assets/9f319dfe-414a-4b85-b95b-55d3fbd945be" />

**Comment by wendefeuer** [comment]
Same here

**Comment by mikkopai** [comment]
I have had this ongoing through different versions as well. Last night it started exactly at midnight, coincidence? At three o'clock shut down Studio Code Server, had been running for a few days. Happens every so often.

Reported here, since 1002 has been closed as duplicate to this.

<img width="496" height="364" alt="Image" src="https://github.com/user-attachments/assets/2a63bc79-d805-43c3-b91a-499be46a58ba" />

<img width="1071" height="442" alt="Image" src="https://github.com/user-attachments/assets/1334e5bd-5f58-42bf-8178-8568a8600f49" />

**Comment by gpt-and-me** [comment]
<img width="1219" height="322" alt="Image" src="https://github.com/user-attachments/assets/6a955e7b-d47d-4dba-83b7-013553184997" />

<img width="1575" height="943" alt="Image" src="https://github.com/user-attachments/assets/92b4084b-98ed-46c0-bf40-0f6d0c55a3a0" />

Noticed system was consuming all the available CPU.  Tracked it down to the Vscode process.
1. Restart Studio Code Server add-on.
2. Open Studio Code through HA ingress.
3. Observe one vscode-home-assistant server.js process.
4. Navigate to another HA sidebar item.
5. Return to Studio Code Server.
6. Observe an additional server.js/extensionHost process.
7. Repeat — process count increases each time.
8. Old processes remain alive.
9. CPU/RAM eventually climb until the add-on is restarted.

Studio Code Server v6.0.1
Core 2026.8.0
Supervisor 2026.07.5
Operating System 18.2
